### ISSUE TITLE
Lien de téléchargement de Qt

### ISSUE THREAD

**Issue by Dysta** [aalex420/QtStatic#1]
j'ai utilisé ton script pour build une version static de qt (merci), mais j'ai du batailler un peu sur le lien de dl car j'avais en retour une erreur 302 (redirection d'url).
J'ai au final trouvé le lien pour ne plus avoir cette erreur et télécharger l'archive directement sur les serveurs de Qt et non des vieux miroirs.
Voici le lien :  http://download.qt-project.org/official_releases/qt/5.11/5.11.0/single/qt-everywhere-src-5.11.0.zip

Merci encore !

**Comment by SmathiLagui** [comment]
Bonjour (désolé pour cette réponse un peu tardive, je viens seulement de voir ce message),
L'adresse que tu donnes qt-project.org redirige vers qt.io donc il faut utiliser l'adresse https://download.qt.io/official_releases/qt/5.11/5.11.0/single/qt-everywhere-src-5.11.0.zip.
Ou plus simplement pour télécharger les sources il est possible d'utiliser le maintenance tool inclus dans Qt (mais les source ne seront pas dans un fichier zip car déjà extraites).

Au plaisir de t'avoir aidé :)
